### ISSUE TITLE
Strange problem with docker

### ISSUE THREAD

**Issue by sprootik** [docker/desktop-linux#107] opened 2022-12-14 13:24 UTC
Hi all. Docker version 20.10.21, build baeda1f82a Caught some strange problem. There is an image alpine:latest I start docker
```
❯ docker run -it --rm --name test alpine:latest
sh-5.1# printenv
HOSTNAME=129487e4b428
PWD=/
HOME=/root
TERM=xterm
SHLVL=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/sbin/printenv
sh-5.1# 
sh-5.1# apk -V
sh: apk: command not found
sh-5.1# ls -l /sbin | grep apk
sh-5.1# 
```

The same machine, only in podman with the same image
```
❯ podman run -it --rm --name test alpine:latest
/ # printenv 
HOSTNAME=2d09127e0ed0
SHLVL=1
HOME=/root
container=podman
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
/ # apk -V
apk-tools 2.12.10, compiled for x86_64.
/ # ls -l /sbin | grep apk
-rwxr-xr-x    1 root     root         69560 Oct 23 19:14 apk
/ # 
```

Apparently, the problem appeared after updating the version of docker, since everything was fine before, I did not use docker for some time. But the thought does not let me go that I messed up somewhere, however, I have no idea what and where to look for.

**Comment by p1-0tr** [comment] 2022-12-14 13:43
This looks like an engine issue.

@thaJeztah - I don't have rights to transfer this issue. Are you able to help with this?

**Comment by sprootik** [comment] 2022-12-14 13:49
*upd
I use Manjaro linux. Linux workLP 5.19.17-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Nov 6 00:08:27 UTC 2022 x86_64 GNU/Linux

**Comment by thaJeztah** [comment] 2022-12-14 14:22
The docker engine issue tracker is in the moby org, so unfortunately it's not possible to transfer the ticket.

@sprootik would you be able to open a new ticket in https://github.com/moby/moby, and to provide the additional details (full output of `docker version` and `docker info` at least, and if possible daemon logs)?

**Comment by sprootik** [comment] 2022-12-14 23:39
I did https://github.com/moby/moby/issues/44647

**Comment by thaJeztah** [comment] 2022-12-15 09:22
Looks like it was resolved (no longer reproducible), so let me close this ticket 👍

**Closed by thaJeztah** 2022-12-15 09:22 UTC
