### ISSUE TITLE
Impossible to push image with a dash on path

### ISSUE THREAD

**Issue by baiiko** [docker/desktop-linux#141] opened 2023-04-17 12:42 UTC
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Hey people,

I have a similar bug on github actions and on my computer.
I try to push an image with my oldes github name : GuigZ-, but i can not.

```sh
> $ docker build -f ./docker/php/Dockerfile -t docker.pkg.github.com/guigz-/foobar:latest ./docker/php/
```

I have got this error :

```
ERROR: invalid tag "docker.pkg.github.com/guigz-/foobar:latest": invalid reference format
```

### Information

  - Linux distro: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
  - Docker Desktop Version:
  Version 4.11.0 (83626)Engine: 20.10.17
  Compose: v2.7.0
  Credential Helper: v0.6.4
  Kubernetes: v1.24.2

**Comment by baiiko** [comment] 2023-04-17 14:22
Lot of users use dahs or underscore at the end of his username 😨 

It's a very strange rule :/ 

I go open an issue on github 🤣

**Comment by thaJeztah** [comment] 2023-04-17 14:35
Ahm, yes, that's an interesting situation indeed. 

I know the original reason for disallowing separators at the start / end was to _at least_ prevent leading hyphens, as they could easily conflict with command-line options when using the "common-name" format (e.g. `docker push --hello/myimage`). Given that it's easier to become _less_ restrictive than  _more_ restrictive (without breaking backward compatibility), we decided to only allow hyphens to be used as _separator_ (and disallow both at the start and end). _Technically_ it would be possible to allow these, but that will require a change in the specification (and it will take time before that's supported everywhere).

I'll close this ticket here, because it's not a bug, but feel free to continue the conversation.

**Closed by thaJeztah** 2023-04-17 14:35 UTC
